### ISSUE TITLE
Crash When Building and Solving Models

### ISSUE THREAD

**Issue by DHarwell** [rconcep/snl-quest#1]
In this particular crash, using the QuESt Valuation Wizard, ERCOT, HB_HOUSTON, Arbitrage and regulation, 2018, Li-ion Battery. However it has shown up on several different market areas and on a couple of different computers. Also tried the 1.1 release as well as the master

Console output follows:
[INFO   ] [Logger      ] Record log in C:\Users\dharwell\.kivy\logs\kivy_19-03-06_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 22.20.16.4771'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 520'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 22.20.16.4771'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [DMS         ] Successfully loaded valuation_dms.p.
[INFO   ] [Base        ] Start application main loop
[INFO   ] [DataManager ] Data bank scan complete.
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [ValuationWizard] ISO changed to ERCOT.
[INFO   ] [ValuationWizard] Pricing node changed to HB_HOUSTON (ID: HB_HOUSTON).
[INFO   ] [ValuationWizard] Market formulation changed to Arbitrage and regulation.
[INFO   ] [ValuationWizard] Changed historical data set to 2018.
[INFO   ] [ValuationWizard] Energy storage device changed to Li-ion Battery.
[INFO   ] [DMS         ] Loading ERCOT DA-SPP
[INFO   ] [DMS         ] Data located in DMS, retrieving...
[INFO   ] [DMS         ] Loading ERCOT DA-CCP
[INFO   ] [DMS         ] Data located in DMS, loading...
[INFO   ] [Optimizer   ] Setting Power_rating to 36.0
[INFO   ] [Optimizer   ] Setting Energy_capacity to 24.0
[INFO   ] [Optimizer   ] Setting Round_trip_efficiency to 90.0
[INFO   ] [Optimizer   ] Setting Self_discharge_efficiency to 100.0
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 526, in <module>
     QuEStApp().run()
   File "C:\Python37\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "C:\Python37\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "C:\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "C:\Python37\lib\site-packages\kivy\base.py", line 337, in idle
     Clock.tick()
   File "C:\Python37\lib\site-packages\kivy\clock.py", line 581, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "C:\Python37\lib\site-packages\kivy\animation.py", line 352, in _update
     self.stop(widget)
   File "C:\Python37\lib\site-packages\kivy\animation.py", line 217, in stop
     self.dispatch('on_complete', widget)
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "C:\Python37\lib\site-packages\kivy\uix\screenmanager.py", line 419, in _on_complete
     self.screen_in.dispatch('on_enter')
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Temp\snl-quest-1.1\es_gui\apps\valuation\wizard.py", line 935, in on_enter
     self.execute_run()
   File "C:\Temp\snl-quest-1.1\es_gui\apps\valuation\wizard.py", line 967, in execute_run
     self.solved_ops, handler_status = valop_handler.process_requests(handler_requests)
   File "C:\Temp\snl-quest-1.1\es_gui\apps\valuation\op_handler.py", line 121, in process_requests
     solved_op = self._solve_model(op)
   File "C:\Temp\snl-quest-1.1\es_gui\apps\valuation\op_handler.py", line 138, in _solve_model
     op.run()
   File "C:\Temp\snl-quest-1.1\es_gui\tools\optimizer.py", line 79, in run
     self.populate_model()
   File "C:\Temp\snl-quest-1.1\es_gui\tools\valuation\valuation_optimizer.py", line 531, in populate_model
     self.model.objective_expr = NumericConstant(0.0)
 NameError: name 'NumericConstant' is not defined

**Comment by rconcep** [comment]
Sorry for missing this. This issue was based on a newer version of Pyomo where the NumericConstant was removed. It should be addressed in the newest release (v1.2).
