### ISSUE TITLE
AssertionError on launch with Kivy v1.11.0

### ISSUE THREAD

**Issue by rconcep** [rconcep/snl-quest#10]
After today's release of Kivy v1.11.0, an AssertionError occurs on launch when running with that version of Kivy.

```
 Traceback (most recent call last):
   File "main.py", line 558, in <module>
     QuEStApp().run()
   File "C:\Users\ricky\Anaconda3\lib\site-packages\kivy\app.py", line 827, in run
     self.load_config()
   File "C:\Users\ricky\Anaconda3\lib\site-packages\kivy\app.py", line 700, in load_config
     self.build_config(config)
   File "main.py", line 494, in build_config
     config.setdefaults('data_manager_pjm', {'pjm_subscription_key': ''})
   File "C:\Users\ricky\Anaconda3\lib\site-packages\kivy\config.py", line 511, in setdefaults
     self.adddefaultsection(section)
   File "C:\Users\ricky\Anaconda3\lib\site-packages\kivy\config.py", line 544, in adddefaultsection
     assert("_" not in section)
 AssertionError
```

We'll have to look into what changes cause issues after this update.

**Comment by rconcep** [comment]
Addressed in v1.2.d
