### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by homdx** [rconcep/snl-quest#2]
`python main.py`
```
/home/user/Android/venv3/lib/python3.6/site-packages/kivy/data/images/defaulttheme.atlas
 Traceback (most recent call last):
   File "main.py", line 558, in <module>
     QuEStApp().run()
   File "/home/user/Android/venv3/lib/python3.6/site-packages/kivy/app.py", line 800, in run
     root = self.build()
   File "main.py", line 504, in build
     sm = QuEStScreenManager(transition=RiseInTransition(duration=0.2, clearcolor=[1, 1, 1, 1]))
   File "main.py", line 208, in __init__
     self.about_screen = AboutScreen()
   File "main.py", line 184, in __init__
     third_party_code_licenses])
 AttributeError: 'AboutScreen' object has no attribute 'about_label'
```

**Comment by rconcep** [comment]
Hi there,

If you could provide me with as much of the following information, that would be helpful for troubleshooting:
-Operating system, device type (e.g., Apple Macbook Pro, etc.)
-Python version
-QuESt version
-~Traceback or error messages from the terminal/command prompt~
-Steps to replicate the issue

**Comment by foad77** [comment]
I have the same issue. in python 3.7, Quest f 1.2. the operating system is  Linux mint 19.
here is the error:


 Traceback (most recent call last):
   File "main.py", line 503, in <module>
     QuEStApp().run()
   File "/home/lenovo/anaconda3/lib/python3.7/site-packages/kivy/app.py", line 829, in run
     root = self.build()
   File "main.py", line 449, in build
     sm = QuEStScreenManager(transition=RiseInTransition(duration=0.2, clearcolor=[1, 1, 1, 1]))
   File "main.py", line 224, in __init__
     self.about_screen = AboutScreen()
   File "main.py", line 201, in __init__
     third_party_code_licenses])
