### ISSUE TITLE
Crash when starting the valuation wizard

### ISSUE THREAD

**Issue by rdtrevi** [rconcep/snl-quest#8]
(base) ...\snl-quest-BTM-UI>python main.py
[INFO   ] [Logger      ] Record log in C:\Users\rdtrevi\.kivy\logs\kivy_19-05-17_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 25.20.100.6472'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) UHD Graphics 620'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 25.20.100.6472'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [GL          ] Unpack subimage support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 556, in <module>
     QuEStApp().run()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\app.py", line 826, in run
     runTouchApp()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\base.py", line 340, in idle
     self.dispatch_input()
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\base.py", line 291, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "...\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\lang\builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "...\snl-quest-BTM-UI\es_gui\apps\valuation\wizard.kv", line 80, in <module>
     root._next_screen()
   File "...\snl-quest-BTM-UI\es_gui\apps\valuation\wizard.py", line 66, in _next_screen
     self.manager.current = 'iso_select'
   File "kivy\properties.pyx", line 483, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 524, in kivy.properties.Property.set
   File "kivy\properties.pyx", line 579, in kivy.properties.Property.dispatch
   File "kivy\_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "C:\Users\rdtrevi\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\screenmanager.py", line 1050, in on_current
     self.transition.start(self)
   File "C:\Users\rdtrevi\AppData\Local\Continuum\anaconda3\lib\site-packages\kivy\uix\screenmanager.py", line 377, in start
     self.screen_in.dispatch('on_pre_enter')
   File "kivy\_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "C:\Users\rdtrevi\Documents\QuESt\snl-quest-BTM-UI\es_gui\apps\valuation\wizard.py", line 121, in on_pre_enter
     ISO_OPTIONS = App.get_running_app().data_manager.get_markets()
   File "C:\Users\rdtrevi\Documents\QuESt\snl-quest-BTM-UI\es_gui\apps\data_manager\data_manager.py", line 195, in get_markets
     return self.data_bank['valuation'].keys()
 KeyError: 'valuation'

**Comment by rconcep** [comment]
Hello,
Is it correct to assume that this is from a fresh install? Based on my investigation, this is due to not having any data downloaded from QuESt Data Manager. If you download any ISO/RTO market data it should fix the issue.

Thanks for the report.

**Comment by rconcep** [comment]
Addressed in v1.2.d
