### ISSUE TITLE
About Running QuESt

### ISSUE THREAD

**Issue by KevinXo** [rconcep/snl-quest#9]
Dear sir,
      Please help me! When I run QuESt,the following situation has occurred.
(base) C:\ProgramData\Anaconda3\Lib\site-packages\snl-quest-master>python main.py
[INFO   ] [Logger      ] Record log in C:\Users\Kevin_xo\.kivy\logs\kivy_19-06-02_0.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - ImportError: DLL load failed: 找不到指定的模块。
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\core\window\window_sdl2.py", line 26, in <module>
    from kivy.core.window._window_sdl2 import _WindowSDL2Storage

[CRITICAL] [App         ] Unable to get a Window, abort.
[ERROR  ]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 412, in execute_directives
    value = eval(value, global_idmap)
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\metrics.py", line 142, in sp
    return dpi2px(value, 'sp')
  File "kivy\properties.pyx", line 291, in kivy.properties.dpi2px
  File "kivy\properties.pyx", line 296, in kivy.properties.dpi2px
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\utils.py", line 496, in __get__
    retval = self.func(inst)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\metrics.py", line 174, in dpi
    EventLoop.ensure_window()
  File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 125, in ensure_window
    sys.exit(1)
SystemExit: 1
 Traceback (most recent call last):
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 412, in execute_directives
     value = eval(value, global_idmap)
   File "<string>", line 1, in <module>
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\metrics.py", line 142, in sp
     return dpi2px(value, 'sp')
   File "kivy\properties.pyx", line 291, in kivy.properties.dpi2px
   File "kivy\properties.pyx", line 296, in kivy.properties.dpi2px
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\utils.py", line 496, in __get__
     retval = self.func(inst)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\metrics.py", line 174, in dpi
     EventLoop.ensure_window()
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\base.py", line 125, in ensure_window
     sys.exit(1)
 SystemExit: 1

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "main.py", line 61, in <module>
     Builder.load_file(os.path.join(dirname, 'es_gui', 'resources', 'widgets', 'common.kv'))
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 301, in load_file
     return self.load_string(data, **kwargs)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 368, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 392, in __init__
     self.parse(content)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 498, in parse
     self.execute_directives()
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\lang\parser.py", line 415, in execute_directives
     raise ParserException(self, ln, 'Invalid value')
 kivy.lang.parser.ParserException: Parser: File "C:\ProgramData\Anaconda3\Lib\site-packages\snl-quest-master\es_gui\resources\widgets\common.kv", line 55:
 ...
      53:
      54:# Font sizes.
 >>   55:#:set default_font sp(20)
      56:#:set stnd_font sp(22)
      57:#:set large_font sp(30)
 ...
 Invalid value
What should I do?

**Comment by KevinXo** [comment]
Dear sir,
now I encounter a new problem.
(base) C:\ProgramData\Anaconda3\Lib\site-packages\snl-quest-master>python main.py
[INFO   ] [Logger      ] Record log in C:\Users\Kevin_xo\.kivy\logs\kivy_19-06-02_3.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "C:\ProgramData\Anaconda3\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\ProgramData\Anaconda3\python.exe"
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.17
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.1.9
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.22
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
libpng warning: iCCP: known incorrect sRGB profile
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 - Build 24.20.100.6286'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 630'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 - Build 24.20.100.6286'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 558, in <module>
     QuEStApp().run()
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 827, in run
     self.load_config()
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\app.py", line 700, in load_config
     self.build_config(config)
   File "main.py", line 494, in build_config
     config.setdefaults('data_manager_pjm', {'pjm_subscription_key': ''})
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\config.py", line 511, in setdefaults
     self.adddefaultsection(section)
   File "C:\ProgramData\Anaconda3\lib\site-packages\kivy\config.py", line 544, in adddefaultsection
     assert("_" not in section)
 AssertionError

What should I do?

**Comment by rconcep** [comment]
Hello,

Regarding your most recent issue, based on my understanding, this issue is due to the new version of Kivy (1.11.0) that was released today. We're going to have to look into what changes this version brought and fix any issues.

If you are on Windows 10, I recommend trying the executable version of QuESt. You can find it in the Releases section:
https://github.com/rconcep/snl-quest/releases/tag/1.2.c

Download the `snl-quest-1.2.c-win10.zip` file, extract it, and run the `snl-quest-v1.2.c.exe` file. This executable comes packaged with its own Python environment and Kivy installation so it should get you started with the GUI at least. You'll still need to have a solver compatible with Pyomo installed if you want to run optimization analysis; please refer to the ReadMe for that.

**Comment by KevinXo** [comment]
Thank you sir,
I have run QuESt successfully.But I am not good at using it.
